### ISSUE TITLE
Update Docker workflow to push to GitHub Container Registry

### ISSUE THREAD

**Issue by khaos-codi** [iksnae/book-builder#3]
## Problem

The current build process for the `actual-intelligence` project is failing because it's trying to use the Docker image `ghcr.io/iksnae/book-builder:latest` from GitHub Container Registry, but the workflow in this repository only pushes to Docker Hub, not to GitHub Container Registry.

## Solution

Update the `.github/workflows/docker-publish.yml` file to push to both Docker Hub and GitHub Container Registry.

Here's the updated workflow file:

```yaml
name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            iksnae/book-builder
            ghcr.io/iksnae/book-builder
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

## Steps to implement

1. Update the `.github/workflows/docker-publish.yml` file with the content above
2. Commit and push the changes to the `main` branch
3. Manually trigger the workflow to build and push the image to both Docker Hub and GitHub Container Registry
4. Once the image is pushed to GitHub Container Registry, the build for the `actual-intelligence` project should work

## Additional Notes

This update adds:
- The `workflow_dispatch` trigger to allow manual runs
- Login to GitHub Container Registry 
- `ghcr.io/iksnae/book-builder` as an additional image target in the metadata action
